import 'dart:convert';

import 'package:rick_and_morty/model/episodes.dart';

import 'package:http/http.dart' as http;

class EpisodesServices {
  List<Episodes> episode = [];
  Future<List<Episodes>> fetchEpisodes() async {
    http.Response response = await http.get(
      Uri.parse('https://rickandmortyapi.com/api/episode'),
    );
    if (response.statusCode == 200) {
      var jsonString = response.body;
      episode.addAll(Autogenerated.fromJson(jsonDecode(jsonString)).episode);
    } else {
      throw Exception('Error');
    }
    return episode;
  }
}
