import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:rick_and_morty/model/location.dart';

class LocationServices {
  List<Location> location = [];

  Future<List<Location>> fetchLocation() async {
    http.Response response = await http.get(
      Uri.parse('https://rickandmortyapi.com/api/location'),
    );
    if (response.statusCode == 200) {
      var jsonString = response.body;
      location.addAll(Autogenerated.fromJson(jsonDecode(jsonString)).location);
    } else {
      throw Exception('Error');
    }
    return location;
  }
}
